config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource  :contacts, only: [:new, :create], path_names: { :new => '' }
  resources :articles do
    resources :comments, only: [:new, :create]
  end

  root to: 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

# Blog's articles object
class Article < ApplicationRecord
  validates :title, presence: true
  validates :text,  presence: true
  has_many :comments

  def subject
    title
  end

  def last_comment
    comments.last
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email,   presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new,:create]
  
  def index
    @articles = Article.all
  end
  
  def show
    @article = Article.find(params[:id]) 
  end
  
  def new
  end

  def create
    @article = Article.new article_params
    if @article.valid? 
      @article.save
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# Description/Explanation of Comment class
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :create
  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  private

  def comment_params
    permitted = params.require(:comment).permit(:body)
    permitted[:author] = current_user.username
    permitted
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
    @contact = Contact.new contact_params
    if @contact.valid?
      @contact.save
      redirect_to @contact
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def terms
    end

    def about
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h3>Редактирование статьи: </h3>
<%= form_for :article, url: article_path(@article), method: :put do |f| %>
    <p>
        <%= f.label :title %> <br />
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :text %> <br />
        <%= f.text_area :text %>
    </p>
    <p>
        <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
    </p>
<% end%>

app/views/articles/index.html.erb
<h3>Всякие новости:</h3>

<% @articles.each do |article| %>

<h4>
    <%= article.title %>
</h4>

<p>
    <%= article.text %>
</p>

<p>
    <%= link_to 'Показать', article_path(article) %>
    <%= link_to 'Изменить', edit_article_path(article)%>
    <%= link_to 'Удалить' , article_path(article), method: :delete, data: { confirm: 'Вы уверены?' } %>
</p>

<hr />

<% end %>

app/views/articles/new.html.erb
<h3>Написать статью</h3>
<%= form_for :article, url: articles_path do |f| %>
    <p>
        <%= f.label :title %> <br />
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :text %> <br />
        <%= f.text_area :text %>
    </p>
    <p>
        <%= f.submit 'Опубликовать', class: 'btn btn-primary' %>
    </p>
<% end%>

app/views/articles/show.html.erb
<h3><%= @article.title %></h3>
<p>
    <%= @article.text %>
</p>
<h4>
    Комментарии:
</h4>
<% @article.comments.each do |commment| %>
<b><%= commment.author %></b> (<%= @article.created_at.inspect %>) написал(а):
<p>
    <%= commment.body %>
</p>
<hr />
<% end %>
<h4>
    Высказаться:
</h4>
<%= form_for ([@article, @article.comments.build]) do |f| %>
    <p>
        <!-- <%= f.label :body %> <br /> -->
        <%= f.text_area :body %>
    </p>
    <p>
        <%= f.submit 'Отправить', class: 'btn btn-primary' %>
    </p>
<% end%>

app/views/contacts/create.html.erb
<p>Спасибо!</p>

app/views/contacts/new.html.erb
<h3><%= t('contacts.contact_us') %></h3>
<%= form_for :contact, url: contacts_path do |f| %>
    <% if @contact && @contact.errors.any? %>
    <p>
        <ul>
            <% @contact.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </p>
    <% end %>
    <p>
        <%= f.label :email %> <br />
        <%= f.text_field :email %>
    </p>
    <p>
        <%= f.label :message %> <br />
        <%= f.text_area :message %>
    </p>
    <p>
        <%= f.submit 'Send message' %>
    </p>
<% end%>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <link rel="stylesheet" 
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
      crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  	<div class="container">
      <nav class="navbar navbar-default" role="navigation"> 
        <div class="navbar-header"-->
          <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="/">Бложик</a></li>
            <li>
              <% if user_signed_in? %>
                <%= link_to 'Написать статью', new_article_path() %>
              <% end %>
            </li>
          </ul>  
        </div>
        <div>
          <ul class="nav navbar-nav">
            <li><a href="/contacts">Контакты</a></li>
          </ul>  
        </div>
        <div>
          <ul class="nav navbar-nav">
            <li><a href="/about">О Нас</a></li>
          </ul>  
        </div>
        <div>
          <ul class="nav navbar-nav">
            <li><a href="/terms">Соглашения</a></li>
          </ul>  
        </div>
        <div>
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li>Hello, <%= current_user.username %></li> 
              <li><%= link_to "Выйти", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Войти", new_user_session_path %></li> 
            <% end %> 
          </ul>
        </div>  
      </nav>
      <div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h3>О Нас!</h3>
<p>
    Когда зарплаты растут, валюта в обменниках заканчиватеся - хочется КУШАТЬ!
</p>

app/views/pages/terms.html.erb
<h3>Соглашения использования</h3>
<p>
    Не копировать статьи из всякого зашквара.
</p>

app/views/welcome/index.html.erb
<h1>Some text...</h1>